task_management/task_management/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path 
from  task_app.views import TaskList, TaskDetail, CreateTask, UpdateTask, DeleteTask

urlpatterns = [
    path('admin/', admin.site.urls),

    path('tasks/', TaskList.as_view(template_name = "tasks/index.html"), name='read'),

    path('tasks/detalle/<int:pk>', TaskDetail.as_view(template_name = "tasks/details.html"), name='details'),

    path('tasks/crear', CreateTask.as_view(template_name = "tasks/create.html"), name='create'),

    path('tasks/editar/<int:pk>', UpdateTask.as_view(template_name = "tasks/update.html"), name='update'), 

    path('tasks/eliminar/<int:pk>', DeleteTask.as_view(), name='delete'),

    path('', lambda request: redirect('tasks/')),

]

task_management/task_app/models.py
from django.db import models
from django.utils import timezone

class Task(models.Model):
    PRIORITY_CHOICES = [
        (1, 'Baja'),
        (2, 'Media'),
        (3, 'Alta'),
    ]

    titulo = models.CharField(max_length=255)
    descripcion = models.TextField(blank=True, null=True)
    prioridad = models.IntegerField(choices=PRIORITY_CHOICES, default=2)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_limite = models.DateField(null=True, blank=True)
    completado = models.BooleanField(default=False)

class Meta:
    db_table = 'tasks'

task_management/task_app/views.py
from django.shortcuts import render
from .models import Task
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django import forms

class TaskList(ListView):
    model = Task

class CreateTask(SuccessMessageMixin, CreateView): 
    model = Task 
    form = Task 
    fields = "__all__" 
    success_message = 'Task created succesfully!' 
    def get_success_url(self):        
        return reverse('read')

class TaskDetail(DetailView): 
    model = Task 

class UpdateTask(SuccessMessageMixin, UpdateView): 
    model = Task
    form = Task 
    fields = "__all__"
    success_message = 'Task updated succesfully !'
    def get_success_url(self):               
        return reverse('read') 

class DeleteTask(SuccessMessageMixin, DeleteView): 
    model = Task 
    form = Task
    fields = "__all__"     
    def get_success_url(self): 
        success_message = 'Task deleted succesfully !' 
        messages.success (self.request, (success_message))       
        return reverse('read')

task_management/task_app/templates/tasks/create.html
<head>

    {# Cargamos la librería #} 
    {% load bootstrap4 %} 
  
    {# CSS Bootstrap #} 
    {% bootstrap_css %} </head>
    
    {# Widget Tweaks #}
    {% load widget_tweaks %}
  
    {# Archivos #}
    {% load static %} <!-- STATIC_URL -->
  
  </head>

<body>
  {% include 'tasks/nav.html' %}

  <div class="container pb-2 pt-3" style="background-color: #EFEFEF; border-radius: 15px;">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="titulo" class="txt_negrita">Título</label>
        {{ form.titulo|add_class:"form-control" }}
    </div>
    
    <div class="form-group">
        <label for="descripcion" class="txt_negrita">Descripción</label>
        {{ form.descripcion|add_class:"form-control" }}
    </div>

    <div class="form-group">
        <label for="prioridad" class="txt_negrita">Prioridad</label>
        {{ form.prioridad|add_class:"form-control" }}
    </div>

    <div class="form-group">
        <label for="fecha_limite" class="txt_negrita">Fecha Límite</label>
        {{ form.fecha_limite|add_class:"form-control"|attr:"type:date" }}
    </div>    

    <button type="submit" class="btn btn-primary">Aceptar</button>
    <a href="./" class="btn btn-secondary">Cancelar</a>
    </form>


  </div>
  <!-- Al final del body -->
{# JS y jQuery Bootstrap #}
{% bootstrap_javascript jquery='full' %} 
</body>

task_management/task_app/templates/tasks/details.html
<head>

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %} </head>

{# Widget Tweaks #}
{% load widget_tweaks %}

{# Archivos #}
{% load static %} <!-- STATIC_URL -->

</head>

<body>
    {% include 'tasks/nav.html' %}

    <div class="container pb-2 pt-3" style="background-color: #EFEFEF; border-radius: 15px;">
        <h4>Detalles de la Tarea</h4>
        <p><span style="font-weight: 500;">Título:</span> <br> {{ object.titulo }}</p>
        <p><span style="font-weight: 500;">Descripción:</span> <br> {{ object.descripcion }}</p>
        <p><span style="font-weight: 500;">Prioridad:</span> <br> {{ object.get_prioridad_display }}</p>
        <p><span style="font-weight: 500;">Fecha de Creación:</span> <br> {{ object.fecha_creacion }}</p>
        <p><span style="font-weight: 500;">Fecha Límite:</span> <br> {{ object.fecha_limite|default:"No asignada" }}</p>
        <p><span style="font-weight: 500;">Completado:</span> <br>
            {% if object.completado %}
            ✅ Sí
            {% else %}
            ❌ No
            {% endif %}
        </p>
        <a href="../" type="submit" class="btn btn-primary mb-3">Volver</a>

    </div>



    <!-- Al final del body -->
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>

task_management/task_app/templates/tasks/index.html
<head>
    {# Cargamos la librería #} 
    {% load bootstrap4 %} 

    {# CSS Bootstrap #} 
    {% bootstrap_css %} 

    {# Widget Tweaks #}
    {% load widget_tweaks %}

    {# Archivos estáticos #}
    {% load static %}
</head>

{% include 'tasks/nav.html' %}

<body style="background-color: #fff;">
    
    <div class="container">

        <div align="right" class="btn_crear mb-3">
    
            <a href="crear" type="button" class="btn btn-primary">Crear</a> <!-- Botón crear -->
        
        </div>
    
    </div>
    
    <div class="container pb-2" style="background-color: #EFEFEF; border-radius: 15px;">
    
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th style="text-align: center;" width="35%">Título</th>
                    <th style="text-align: center;">Descripción</th>
                    <th style="text-align: center;">Prioridad</th>
                    <th style="text-align: center;">Fecha de creación</th>
                    <th style="text-align: center;">Fecha límite</th>
                    <th style="text-align: center;">Completado</th>
                    <th style="text-align: center;">Acciones</th>
                </tr>
            </thead>
            <tbody style="border-radius: 15px;">
                {% for tasks in object_list %}

                {% if tasks.completado %}
                <tr style="background-color: #DAFDBA;">
                    <td align="center">{{ tasks.titulo }}</td>
                    <td align="center">{{ tasks.descripcion }}</td>
                    <td align="center">
                        {% if tasks.prioridad == 1 %}
                            Baja
                        {% elif tasks.prioridad == 2 %}
                            Media
                        {% else %}
                            Alta
                        {% endif %}
                    </td>
                    <td align="center">{{ tasks.fecha_creacion|date:"d/m/Y H:i" }}</td>
                    <td align="center">{{ tasks.fecha_limite|default:"Sin fecha" }}</td>
                    <td align="center">
                        {% if tasks.completado %}
                            ✅
                        {% else %}
                            ❌
                        {% endif %}
                    </td>
                    <td>
                        <form method="POST" action="eliminar/{{tasks.id}}">
                            {% csrf_token %}
                            <div class="btn-group">
                                <a href="detalle/{{tasks.id}}" title="Ver" class="btn btn-success">Ver</a>
                                <a href="editar/{{tasks.id}}" title="Editar" class="btn btn-primary">Editar</a>
                                <button class="btn btn-danger" onclick="return confirm('¿Estás seguro de eliminar esta tarea?');" type="submit">
                                    Eliminar
                                </button>
                            </div>
                        </form>  
                    </td>
                </tr>
                {% else %}
                <tr style="background-color: #fff;">
                    <td align="center">{{ tasks.titulo }}</td>
                    <td align="center">{{ tasks.descripcion }}</td>
                    <td align="center">
                        {% if tasks.prioridad == 1 %}
                            Baja
                        {% elif tasks.prioridad == 2 %}
                            Media
                        {% else %}
                            Alta
                        {% endif %}
                    </td>
                    <td align="center">{{ tasks.fecha_creacion|date:"d/m/Y H:i" }}</td>
                    <td align="center">{{ tasks.fecha_limite|default:"Sin fecha" }}</td>
                    <td align="center">
                        {% if tasks.completado %}
                            ✅
                        {% else %}
                            ❌
                        {% endif %}
                    </td>
                    <td>
                        <form method="POST" action="eliminar/{{tasks.id}}">
                            {% csrf_token %}
                            <div class="btn-group">
                                <a href="detalle/{{tasks.id}}" title="Ver" class="btn btn-success">Ver</a>
                                <a href="editar/{{tasks.id}}" title="Editar" class="btn btn-primary">Editar</a>
                                <button class="btn btn-danger" onclick="return confirm('¿Estás seguro de eliminar esta tarea?');" type="submit">
                                    Eliminar
                                </button>
                            </div>
                        </form>  
                    </td>
                </tr>
                {% endif %}

                {% endfor %}
            </tbody>
        </table>
        
    </div>
    
    
    
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
    </body>
    


</body>

task_management/task_app/templates/tasks/nav.html
<nav class="nav d-flex justify-content-center mb-3" style="background-color: #012030;">

    <a class="mt-3 mb-3 font-weight-bold" href="../" style="text-decoration: none; color: #fff; font-size: large;">Tareas</a>

</nav>

task_management/task_app/templates/tasks/update.html
<head>

    {# Cargamos la librería #}
    {% load bootstrap4 %}

    {# CSS Bootstrap #}
    {% bootstrap_css %} </head>

{# Widget Tweaks #}
{% load widget_tweaks %}

{# Archivos #}
{% load static %} <!-- STATIC_URL -->

</head>

<body>
    {% include 'tasks/nav.html' %}

    <div class="container pb-2 pt-3" style="background-color: #EFEFEF; border-radius: 15px;">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="titulo" class="txt_negrita">Título</label>
                {{ form.titulo|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="descripcion" class="txt_negrita">Descripción</label>
                {{ form.descripcion|add_class:"form-control" }}
            </div>

            <div class="form-group">
                <label for="fecha_vencimiento" class="txt_negrita">Fecha de Vencimiento</label>
                {{ form.fecha_vencimiento|add_class:"form-control"|attr:"type:date" }}
            </div>

            <div class="form-group">
                <label for="prioridad" class="txt_negrita">Prioridad</label>
                {{ form.prioridad|add_class:"form-control" }}
            </div>

            <div class="form-check mb-3">
                <label class="form-check-label">
                    {{ form.completado|add_class:"form-check-input" }} Completado
                </label>
            </div>

            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
            <a href="../" class="btn btn-secondary">Cancelar</a>
        </form>


    </div>


    <!-- Al final del body -->
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
</body>